name: estudos-microsservicos-workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://leticiaantunesjpeg.github.io/SAP007-data-lovers/'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev

  deploy-hml:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'https://leticiaantunesjpeg.github.io/SAP007-data-lovers/'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG


  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'https://leticiaantunesjpeg.github.io/SAP007-data-lovers/'
    needs: deploy-hml
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
